import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit'; // Use 'type' keyword for import
import type { RootState } from "../../../redux/store.ts"; 
import { fetchBanners } from '../action/BannerAction.ts';
import type { Banner, BannersState } from '../model/BannerModel.ts';

export type Status = 'idle' | 'loading' | 'succeeded' | 'failed';

// Define the initial state with the correct types
const initialState: BannersState = {
  items: [],
  status: 'idle',
  error: null,
};

export const bannerSlice = createSlice({
  name: 'banners',
  initialState,
  reducers: {
    // Synchronous reducers go here if needed
  },
  // Extra reducers handle actions generated by createAsyncThunk
  extraReducers: (builder) => {
    builder
      .addCase(fetchBanners.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchBanners.fulfilled, (state, action: PayloadAction<Banner[]>) => {
        state.status = 'succeeded';
        // Type of action.payload is automatically inferred as Banner[] here
        state.items = action.payload; 
      })
      .addCase(fetchBanners.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message || 'Something went wrong'; // Ensure error is a string
      });
  },
});

// Export selectors (functions to access parts of the state)
// Use the RootState type if you have it defined
export const selectBanners = (state: RootState) => state.banners.items;
export const selectBannerStatus = (state: RootState) => state.banners.status;
export const selectBannerError = (state: RootState) => state.banners.error;

// Export the reducer
export default bannerSlice.reducer;
