import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit'; // Use 'type' keyword for import
import type { RootState } from "../../../redux/store.ts"; 
import type { EventList } from '../model/EventModel.ts';
import { fetchEvent } from '../action/EventsAction.ts';
// Ensure EventState.items can handle an array of EventList
type EventState = {
  items: EventList[] | null;
  status: Status;
  error: string | null;
};

export type Status = 'idle' | 'loading' | 'succeeded' | 'failed';

// Define the initial state with the correct types
const initialState: EventState = {
  items: null,
  status: 'idle',
  error: null,
};

export const eventSlice = createSlice({
  name: 'event',
  initialState,
  reducers: {
    // Synchronous reducers go here if needed
  },
  // Extra reducers handle actions generated by createAsyncThunk
  extraReducers: (builder) => {
    builder
      .addCase(fetchEvent.pending, (state) => {
        console.log("fetch event pending...");
        state.status = 'loading';
      })
      .addCase(fetchEvent.fulfilled, (state, action: PayloadAction<EventList[]>) => {
        state.status = 'succeeded';
        // Assign the array payload to items
        state.items = action.payload; 
      })
      .addCase(fetchEvent.rejected, (state, action) => {
        console.log("fetch event rejected...");
        state.status = 'failed';
        state.error = action.error.message || 'Something went wrong'; // Ensure error is a string
        state.items = null
      });
  },
});

// Export selectors (functions to access parts of the state)
// Use the RootState type if you have it defined
export const selectEvent = (state: RootState) => state.event.items;
export const selectEventStatus = (state: RootState) => state.event.status;
export const selectEventError = (state: RootState) => state.event.error;

// Export the reducer
export default eventSlice.reducer;
