import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit'; // Use 'type' keyword for import
import type { RootState } from "../../../redux/store.ts"; 
import type { EmployeeList, EmployeeState } from '../model/EmployeeModel.ts';
import { fetchEmployee } from '../action/EmployeeAction.ts';

export type Status = 'idle' | 'loading' | 'succeeded' | 'failed';

// Define the initial state with the correct types
const initialState: EmployeeState = {
  items: [],
  status: 'idle',
  error: null,
};

export const employeeSlice = createSlice({
  name: 'employee',
  initialState,
  reducers: {
    // Synchronous reducers go here if needed
  },
  // Extra reducers handle actions generated by createAsyncThunk
  extraReducers: (builder) => {
    builder
      .addCase(fetchEmployee.pending, (state) => {
        console.log("fetchEmployee pending...");
        state.status = 'loading';
      })
      .addCase(fetchEmployee.fulfilled, (state, action: PayloadAction<EmployeeList[]>) => {
        console.log("fetchEmployee fulfilled...");
        state.status = 'succeeded';
        // Type of action.payload is automatically inferred as employee[] here
        state.items = action.payload; 
      })
      .addCase(fetchEmployee.rejected, (state, action) => {
        console.log("fetchEmployee rejected...");
        state.status = 'failed';
        state.error = action.error.message || 'Something went wrong'; // Ensure error is a string
      });
  },
});

// Export selectors (functions to access parts of the state)
// Use the RootState type if you have it defined
export const selectEmployee = (state: RootState) => state.employee.items;
export const selectEmployeeStatus = (state: RootState) => state.employee.status;
export const selectEmployeeError = (state: RootState) => state.employee.error;

// Export the reducer
export default employeeSlice.reducer;
